---
title: "Quick plot for cytometry data"
output:
  html_document:
    fig_height: 2
    fig_width: 5
    keep_md: yes
vignette: >    
  %\VignetteEngine{knitr}
  %\VignetteIndexEntry{Quick plot for cytometry data}    
---

```{r, echo=FALSE}
library(knitr)
opts_chunk$set(message = FALSE, warning = FALSE)
```

```{r}
library(ggcyto)
dataDir <- system.file("extdata",package="flowWorkspaceData")
gs <- load_gs(list.files(dataDir, pattern = "gs_manual",full = TRUE))
data(GvHD)
fs <- GvHD[subset(pData(GvHD), Patient %in%5 & Visit %in% c(5:6))[["name"]]]
```

## `flowSet`
```{r}
## 1d densityplot
autoplot(fs, x = 'FSC-H')

## 2d hex
autoplot(fs, x = 'FSC-H', y = 'SSC-H', bins = 64)
```

## `GatingSet` 
```{r, fig.width = 4, fig.height=3}
# apply the instrument range by default
# use direct parent
# inverse trans axis
autoplot(gs, "CD3+", bins = 64)

# multiple
autoplot(gs, c("CD4", "CD8"), bins = 64)
```

## `GatingHierarchy`
```{r, fig.height = 4}
gh <- gs[[1]]
nodes <- getNodes(gh, path = "auto")[c(3:9, 14)]
nodes
# default use grid.arrange
autoplot(gh, nodes, bins = 64)

# disable arrange and receive a list of ggplot objects to manually arrange
objs <- autoplot(gh, nodes, bins = 64, arrange = FALSE)
length(objs)
class(objs[[1]])
class(objs[[2]])

```

