---
title: "Visualize cytometry data with ggplot2 (advanced)"
author: "Mike Jiang"
date: "04/13/2015"
output: html_document
---

```{r, echo=FALSE}
library(knitr)
opts_chunk$set(message = FALSE, warning = FALSE)
```

`ggCyto` makes `ggplot2` to be able to work with `Cytometry` data, namely `flowSet/ncdfFlowSet` or `flowFrame` S4 objects.


```{r}
library(ggCyto)
data(GvHD)
fs <- GvHD[subset(pData(GvHD), Patient %in%5:7 & Visit %in% c(5:6))[["name"]]]
fr <- fs[[1]]
```

## 1d histogram/densityplot
```{r}
# histogram at raw scale
p <- ggplot(fr, aes(x = `FL1-H`)) 
p + geom_histogram() 

# customize border colors and log scale 
p + geom_histogram(colour = "white") + scale_x_log10()

# change the bin width
p + geom_histogram(colour = "white", binwidth = 1/20) + scale_x_log10()

# logicle scale with default parameters setting (e.g. t = 262144)
p <- p + geom_histogram(colour = "white")
p + scale_x_logicle()

# logicle scale with customized parameter
p + scale_x_logicle(t = 1e4, w = 0)

# customized breaks
myBreaks <- c(0, 10, 1e2, 1e3)
p  + scale_x_logicle(t = 1e4, w = 0, breaks = myBreaks)

# remove marginal events
p  + scale_x_logicle(t = 1e4, w = 0, breaks = myBreaks, limits = c(2, 1e4))

# other scales: flowJo_fasinh, flowJo_biexp
p + scale_x_flowJo_fasinh(T = 1e4)
p + scale_x_flowJo_biexp(maxValue = 1e4, widthBasis = 0)

# save the scales
myScales <- scale_x_logicle(t = 1e4, w = 0, breaks = myBreaks, limits = c(2, 1e4))


# density  (default y is density)
p <- ggplot(fr, aes(x = `FL1-H`)) + myScales
p + geom_density() 

# display area
p + geom_area(stat = "density") 

# display y as count
p + geom_area(stat = "density", aes(y = ..count..))
  
# histogram + density line
ggplot(fr, aes(x = `FL1-H`, y = ..density..)) + geom_histogram(colour = "white") + geom_density(color = "red") + myScales

# plot multiple samples
p <- ggplot(fs, aes(x = `FL1-H`)) + myScales + geom_area(stat = "density")
# facetting by sample names
p + facet_wrap(~name) 

# faceeting by other pheno data stored in fs
p + facet_grid(Patient~Visit)

# fill with different colors
ggplot(fs, aes(x = `FL1-H`, fill = name)) + facet_wrap(~name) +  geom_density(alpha = 0.2) + myScales

# or plot in the same panel
ggplot(fs, aes(x = `FL1-H`, fill = name)) + geom_density(alpha = 0.2) + myScales
```

## 2d scatter/dot plot
```{r}
# 2d hex
p <- ggplot(fr, aes(x = `FSC-H`, y =  `SSC-H`))
p + stat_binhex()

# change the smooth color 
myColor <- rev(RColorBrewer::brewer.pal(11, "Spectral"))
myColor_scale_fill <- scale_fill_gradientn(colours = myColor)
p + myColor_scale_fill + stat_binhex()


#change the bin
p + myColor_scale_fill + stat_binhex(bin = 64)

# sqr trans binned color
myColor_scale_fill_sqrt <- scale_fill_gradientn(colours = myColor, trans = "sqrt")
p1 <- p + myColor_scale_fill_sqrt + stat_binhex(bin = 64)
p1
# add boundary limits
p1 <- p1 + ylim(c(10,9e2)) + xlim(c(10,9e2))   
p1

# add contour
p <- p + myColor_scale_fill
p + stat_binhex(bin = 64) + geom_density2d(colour = "black")

# non-binned dot plot
df <- fortify(fr)
cols <- densCols(df[,"FSC-H"], df[,"SSC-H"], colramp = flowViz::flowViz.par.get("argcolramp"))
p1 <- ggplot(df, aes(x = `FSC-H`, y =  `SSC-H`))
p1 + geom_point(color = cols) 

# multiple samples
p1 <- ggplot(mapping = aes(x = `FSC-H`, y =  `SSC-H`)) + myColor_scale_fill + facet_grid(Patient~Visit)
p1 + stat_binhex(data = fs, bin = 64)
# color scale is different when plotting single sample
p1 + stat_binhex(data = fs[6], bin = 64)

# display density instead
p1 + stat_binhex(data = fs[6], bin = 64, aes(fill = ..density..))
# the color scale difference is reduced
p1 + stat_binhex(data = fs, bin = 64, aes(fill = ..density..))
```

## add overlay
```{r}
# get a gated data
lg <- flowStats::lymphGate(fr, channels=c("FSC-H", "SSC-H"),scale=0.6)
norm.filter <- lg$n2gate
overlay.fr <- lg$x

# add the overlay and dim the background
p1 <- p + stat_binhex(bin = 64, alpha = 0.2)
p1 <- p1 + geom_point(data = overlay.fr, color = "red", cex = 0.5, pch = 19)
p1

# another overlay 
rect.g <- rectangleGate(list("FSC-H" =  c(300,500), "SSC-H" = c(50,200)))
overlay.fr2 <- Subset(fr, rect.g)
p1 + geom_point(data = overlay.fr2, color = "black", cex = 0.5, pch = 19)

# overlay for multiple samples
overlay.fs1 <- Subset(fs, norm.filter)
overlay.fs2 <- Subset(fs, rect.g)
ggplot(fs, aes(x = `FSC-H`, y =  `SSC-H`)) + 
          scale_fill_gradientn(colours = myColor)  +
          stat_binhex(bin = 64, alpha = 0.2) +
          geom_point(data = overlay.fs1, color = "red", cex = 0.5, pch = 19) +
          geom_point(data = overlay.fs2, color = "black", cex = 0.5, pch = 19) +
          facet_grid(Patient ~ Visit)

```

# add gate
```{r}
poly.g <- flowViz:::norm2Polygon(filterDetails(lg[["n2gateResults"]], identifier(norm.filter)))
p <- p + stat_binhex(bin = 64) + ylim(c(10,9e2)) + xlim(c(10,9e2))   

# polygonGate
p1 <- p + geom_gate(data = poly.g)
p1
# 2d rectangleGate
p1 <- p1 + geom_gate(data = rect.g)
p1
# 1d rectangleGate
rect.g1d <- rectangleGate("FSC-H" =  c(550, Inf))
p1 + geom_gate(data = rect.g1d, aes(x = `FSC-H`, y =  `SSC-H`))

```



